### PR TITLE
after install pull request builder plugin

### PR DESCRIPTION
**Pull request by hongtao12310**

### CODE REVIEW

**Comment by OnTheWay2018** [comment]
Jenkins Test

**Comment by OnTheWay2018** [comment]
Can one of the admins verify this patch?

**Comment by OnTheWay2018** [comment]
Test for token for jenkins

**Comment by hongtao12310** [comment]
retest this please

**Comment by OnTheWay2018** [comment]
retest this please

**Comment by OnTheWay2018** [comment]
test

**Pull request merged**
